### ISSUE TITLE
Move Installation guides to docs

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-docs#1]
Move the documentation from https://docs.google.com/document/d/17U84hDU8mliw4lfLBt-NBdUjE-WlGV4bWVLKbYqLkuA/edit#

to docs tutorial

**Comment by eudisley** [comment]
I am passing to a markdown file but I think this guide must be reviewed.

**Comment by eudisley** [comment]
I have finished to move this file to docs. I would suggest we divide it in 4 different pages: Mojaloop, TTP Test Platform, MMO1, MMO2, etc. 

https://gsmainclusivetechlab.github.io/interop-docs/installation

One question: Why there is two installation guides for MMO1? What's the difference?

**Comment by brunosmm** [comment]
Hi Eudis,

Thanks for this update.
Please check with @mbabuta / @agalaguz  about this, they can help you on those
questions.

**Comment by mbabuta** [comment]
Hi Eudis,
Its just a typo in manual. https://gsmainclusivetechlab.github.io/interop-docs/installation/#gsma-mmo1-simulator-1 - steps to install\update SP and should be named as "GSMA SP simulator"
And yes, installation \ updating process of MMO1 and SP is identical

**Comment by eudisley** [comment]
Hi @mbabuta 
I did not understand the typo. May you explain me better please? :D
I will remove the second time MMO1 appears. Please remove also from the doc file. I do not have edit access.

**Comment by mbabuta** [comment]
Fixed https://github.com/gsmainclusivetechlab/interop-docs/blob/master/docs/installation.md
When MMO1 appears in documents for the second time is instructions for SP simulator in fact. I`ve copied MMO1 instructions text and forgot to change name from MMO1 to SP :)

The installation instructions for the MMO1 and SP is very similar. In fact the only difference is in nginx configuration: server__name and reverse_proxy port

**Comment by eudisley** [comment]
Great. Thank you @mbabuta. 
I got it. I will build it here and make the deploy with this change. ;)

**Comment by cjol** [comment]
This was closed in #30.
