### ISSUE TITLE
Update All References to MMO -> FSP

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-docs#52]
Although it is easy to update references to MMO -> FSP within the platform, the documentation will need to be updated manually. I would suggest the following find-and-replace should do it. 

`MMO` -> `FSP`
`Mobile Money Operator` -> `Financial Services Provider`

**Comment by eudisley** [comment]
I will begin this process. Also, we will need to update all screenshots where MMO appears.

**Comment by eudisley** [comment]
@cjol and @SamyBouch 
There are places I dont know yet if MMO will be replaced by FSP, such as: 

$ docker-compose exec mysqldb bash -c "mysqldump -p -u $DB_USERNAME  $DB_DATABASE > /var/lib/mysql/mmo-simulator_`date +%Y-%m-%d`.sql"

Most of them are in the installation guide.

**Comment by cjol** [comment]
That particular line it probably wouldn't matter (it's just the filename used for the backup) but yes; whoever does this needs to be careful about each replacement!

**Comment by eudisley** [comment]
I finished to change the names but I still need to create new images to replace the ones with MMO names.
