### ISSUE TITLE
Broken Pages/Links

### ISSUE THREAD

**Issue by SamyBouch** [gsmainclusivetechlab/interop-docs#59]
Right now if you head over to https://docs.interop.gsmainclusivetechlab.io/ and try to navigate to the "About" page, or the "Test Sessions" and "Test Results" pages in the User Manual section, you will get the "Page Not Found" message.

## Steps to reproduce

1. Head to https://docs.interop.gsmainclusivetechlab.io/
2. Click on either "About", "Test Sessions" or "Test Results"

## Expected outcome

The correct markdown files should be displayed at /home, manual/session and manual/results

## Actual outcome

Site responds back with "Page not found". I found that if the `homePageId` parameter is removed here 

https://github.com/gsmainclusivetechlab/interop-docs/blob/d521093fb8381124172a6dc743ab33819e69fe13/docusaurus.config.js#L88-L91

the '/home' page will show up correctly but then '/' becomes a blank page, so maybe the problem has to do with that in some way. As for the other two I haven't been able to reproduce them locally so I'm not sure what the issue is there.

**Comment by cjol** [comment]
Fixed in 9c5c989bd5cc3bf36d907d475a01fcb59f44c645
